### ISSUE TITLE
support require.resolve

### ISSUE THREAD

**Issue by thlorenz** [substack/brfs#13]
As an example I currently have this code:

```js
// TODO: a bit brittle if jsoneditor is deduped for instance
var css = fs.readFileSync(__dirname + '/../node_modules/jsoneditor/jsoneditor.css');
loadCSS(css);
```

The below would be a lot less brittle:

```js
var css = fs.readFileSync(require.resolve('jsoneditor') + '/jsoneditor.css');
loadCSS(css);
```

Just checking if this is in scope and discuss best way to make this work.
I'll jump at implementing and PRing this feature if you agree that this makes sense.

**Comment by substack** [comment]
`require.resolve()` is now supported in 1.4.0.

**Comment by qubyte** [comment]
Splendid! Thanks muchly. :D
