### ISSUE TITLE
Error: unsupported type for static module: VariableDeclarator

### ISSUE THREAD

**Issue by humidair1999** [substack/brfs#24]
Getting this error both in `brfs` `1.1.0` and `1.1.1`. I'm on Windows 7, 64-bit.

I'm building my `browserify` bundle from the command line, using the `-t brfs` flag. I don't even have any `require('fs')` statements in my code yet; this error is thrown regardless, due to the transform.

The error is not thrown on `1.0.2` and older versions.

**Comment by obartra** [comment]
Could this issue have regressed? I can repro the error on versions 1.4.2 and 1.4.3 but not on 1.0.2 as indicated above.

**Comment by cavneb** [comment]
+1 on regression
