### ISSUE TITLE
Does not work in single var statement defining multiple variables

### ISSUE THREAD

**Issue by jgillich** [substack/brfs#25]
The example provided in the README works fine, but the following does not:

    var fs = require('fs'),
        html = fs.readFileSync('./robot.html', 'utf8');
    console.log(html);

    // Compiled to:
    var html = fs.readFileSync('./robot.html', 'utf8');
    console.log(html);

I am not sure if this is a browserify limitation or an actual bug though.

**Comment by mattdesl** [comment]
Testing brfs@1.4.0 with the following and not able to reproduce this bug:

```js
var fs = require('fs'),
  data = fs.readFileSync('./data.txt', 'utf8')
console.log(data)
```
