### ISSUE TITLE
Upgrade 0.0.9 -> 1.2.0 gives node runtime error 'cannot find esprima'

### ISSUE THREAD

**Issue by dizzib** [substack/brfs#33]
This is because I run `npm prune` before `npm install` and brfs 1.2.0 depends on static-module ^1.0.0 which depends on falafel ~0.3.1 which has a bug https://github.com/substack/node-falafel/pull/24 whereas brfs 0.0.9 depends on falafel ~0.1.6 which doesn't have this bug.

**Comment by substack** [comment]
Shouldn't be a problem anymore now that falafel uses acorn.
