### ISSUE TITLE
fs is not defined error when readFileSync is passed a path variable

### ISSUE THREAD

**Issue by stewartknapman** [substack/brfs#36]
I'm getting the following error when I run this with the brfs transform.

    var temp = fs.readFileSync(template_path, 'utf8');
               ^
    ReferenceError: fs is not defined
    ...

Test 1:

    var fs  = require('fs');
    var temp = fs.readFileSync('./templates/test.html', 'utf8');
    console.log(temp);

If I run this with `node test.js`, or

    browserify test.js -o output.js -t brfs
    node output.js

I get the expected 'hello world' content from test.html output to the console.
The contents of output.js looks like this:

    (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
    
    /* Test 1 */
    var temp = "hello world";
    console.log(temp);
    
    },{}]},{},[1]);

However if I do the same with Test 2:

    var fs  = require('fs');
    var template_path = './templates/test.html';
    var temp = fs.readFileSync(template_path, 'utf8');
    console.log(temp);

`node test.js` works fine but running browserify and then `node output.js` gives me the fs is not defined error.
Also output now looks like this:

    (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
    
    /* Test 2 */
    
    var template_path = './templates/test.html';
    var temp = fs.readFileSync(template_path, 'utf8');
    console.log(temp);
    
    },{}]},{},[1]);

**Comment by feross** [comment]
Would be cool if we could at least support this use case:

```js
fs.readFileSync(path.join(__dirname, 'txt', 'file.txt'))
```

**Comment by substack** [comment]
`path.join()` is now supported, assuming you `var path = require('path')` beforehand.

**Comment by feross** [comment]
This is excellent!

**Comment by RichardLitt** [comment]
I'm getting an error when passing path.join():

```js
runtime.path = path.join(__dirname, "example.js");

function compile(source, options) {
  options = normalizeOptions(options);

  if (!genOrAsyncFunExp.test(source)) {
    return {
      // Shortcut: no generators or async functions to transform.
      code: (options.includeRuntime === true ? fs.readFileSync(
        runtime.path, "utf-8"
      ) + "\n" : "") + source
    };
  }
...
``` 

Is this expected, given the fix above?

**Comment by yoaquim** [comment]
Getting an error when using `path.join()`. Maybe I'm not using it correctly? Can you include string variables in `path.join()`, which would in turn let you, indirectly, use variables in `readFileSync()`?

**Comment by gregorskii** [comment]
Ditto. Seeing an error even when using path.join.

**Comment by leedorian** [comment]
path.join does not work for variables too.

**Comment by matisoffn** [comment]
I'm having this same problem.  Using this library to render HTML templates from a JavaScript function that's triggered based on route change.

Code that works:

```javascript
var location = window.location.hash.slice(2)

var template = fs.readFileSync('app/templates/accounts/login.tpl', 'utf8')

console.log(template)

$('#app').html(template)
```

But when I change the `var template` line to the below it does not work:

```javascript
var template = fs.readFileSync('app/templates/' + location + '.tpl', 'utf8')
```

**Comment by mattdesl** [comment]
You can't use variables since the expression has to be statically analyzable, i.e. Known at build time, not run time.

**Comment by matisoffn** [comment]
Alternatives?

**Comment by mattdesl** [comment]
Depends what you are doing... You can use bulkify to bulk-require a whole folder at build time, or write your own server if you need more flexibility. 

For HTML templates most people just have them all available at runtime and accessible by a key, eg with handlebars.

**Comment by matisoffn** [comment]
Hey @mattdesl ,

Thanks for your help and the suggestion.

Check out my comment above, you'll see the use case.

Any idea what to do?  Seems like maybe I can't get the job done with just brfs.

**Comment by dwiyatci** [comment]
D'oh. Does not work for me either. :disappointed:

```javascript
var viewTemplate = fs.readFileSync(
        __dirname + location.href.match(/index_dev.html/i) ?
        '/tmpl/view.tmpl.html' : '/tmpl/view.tmpl.min.html', 'utf8');
```

**Comment by ibc** [comment]
Guys, is it so hard to understand? `brfs` works at "build" time so it does not eval the JavaScript code within the arguments to `fs.readFileSync()`.

**Comment by matisoffn** [comment]
@ibc I completely understand and I think others do as well, however people are still going to post to look for alternatives.  Rather than getting frustrated with that, lets post some good alternatives since this package won't work for that use case.

I was using the router Director and trying to render templates based on certain routes (using brfs).  Since brfs wouldn't work because it needed to dynamically render the file, I searched for other solutions.

I'm using Vue.js, so I resorted to vue-router rather than using Director.  This probably won't help many of you since it's Vue.js specific, but I may as well explain how I got around it.

**Comment by dwiyatci** [comment]
Yeah, I guess we were just being frustrated there. For me, I ended up in setting up a grunt task to watch for the templates changes, always `readFileSync()` the minified ones in the JS code, and then re-bundle. A bit too much of CPU overhead during the development, but yeah. Boiled down to something like:

```javascript
var fs = require('fs');
var viewTemplate = fs.readFileSync(
    __dirname + '/tmpl/view.tmpl.min.html', 'utf8');
```

**Comment by loretoparisi** [comment]
This issue has been closed, but why???
The problem is still there:

```shell
macbookproloreto:node-pokemap admin$ cat test.js
 var fs  = require('fs');
 var temp = fs.readFileSync('./test.json', 'utf8');
 console.log(temp);
macbookproloreto:node-pokemap admin$ node test
{ key : hello world }

macbookproloreto:node-pokemap admin$ browserify test.js -o output.js -t brfs
macbookproloreto:node-pokemap admin$ node output
{ key : hello world }

macbookproloreto:node-pokemap admin$ cat output.js 
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
 
 var temp = "{ key : hello world }\n";
 console.log(temp);

},{}]},{},[1]);
macbookproloreto:node-pokemap admin$ cat test2.js
 var fs  = require('fs');
 var filename='./test.json';
 var temp = fs.readFileSync(filename, 'utf8');
 console.log(temp);
macbookproloreto:node-pokemap admin$ node test2
{ key : hello world }

macbookproloreto:node-pokemap admin$ browserify test2.js -o output2.js -t brfs
macbookproloreto:node-pokemap admin$ node output2
/output2.js:4
 var temp = fs.readFileSync(filename, 'utf8');
            ^

ReferenceError: fs is not defined
    at Object.__dirname.1 (/output2.js:4:13)
    at s (/output2.js:1:316)
    at e (/output2.js:1:487)
    at Object.<anonymous> (/output2.js:1:505)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
```

wepack version is 

```shell
macbookproloreto:node-pokemap admin$ cat node_modules/webpack/package.json | grep id
  "_id": "webpack@1.13.1",
    "webpack-dev-middleware": "^1.0.0",
```

**Comment by loretoparisi** [comment]
@ibc ok I see that since it works at build time there is no `eval` of expressions like

```javascript
/**
         * Load an Apache2-style ".types" file
         *
         * This may be called multiple times (it's expected).  Where files declare
         * overlapping types/extensions, the last file wins.
         *
         * @param file (String) path of file to load.
         */
        Mime.prototype.load = function(file) {
          // Read file and split into lines
          var map = {},
              content = fs.readFileSync(file, 'ascii'),
              lines = content.split(/[\r\n]+/);

          lines.forEach(function(line) {
            // Clean up whitespace/comments, and split into fields
            var fields = line.replace(/\s*#.*|^\s*|\s*$/g, '').split(/\s+/);
            map[fields.shift()] = fields;
          });

          this.define(map);
        };
```

the fact is that tons of modules have the `fs.readFileSync` in the code, so I don't get which is the solution here, and why this issue has been closed without any working/possible (proposal of )a solution.

**Comment by ibc** [comment]
> I don't get which is the solution here, and why this issue has been closed without any working/possible (proposal of )a solution.

It's been closed because `brfs` has never been supposed to handle dynamic runtime variables and, hence, there is no bug to fix here nor and the author has not the responsibility of providing a solution/proposal/workaround.

**Comment by vishalya** [comment]
phantomjs has it's own api - it's not the same as node api.
read method is equivalent of readFileSync
http://phantomjs.org/api/fs/

**Comment by sebs** [comment]
You can close this a 20 times. I must second @ibc . Its not helping (and prolly causing bugs in repos using BRTFS)

**Comment by onojatreasure** [comment]
`var fs = require('fs');`
Is compulsory at the beginning of the code
Also, the first argument must be a string. Not a concatenated variable, not a variable. It must completely be string.

**Comment by Vyshakhcs1** [comment]
The fs npm module is stopped their service. They are saying,
**This package name is not currently in use, but was formerly occupied by another package. To avoid malicious use**

**Comment by aflansburg** [comment]
fs is actually a part of the Node API ecosystem. The fs npm name is just reserved for obvious reasons.

**Comment by Prashant-Kan** [comment]
Hello Guys, 
I am facing a similar problem 
I have imported "fs" using import * as fs from "fs" and trying to execute fs.readFile() and fs.readFileSync with there respective arguments. 
But, getting an error as "fs" object doesn't have a function readFile() and readFileSync(). 
I have tried using var fsFile = require("fs");.

I am using in Cypress automation project in typescript.

**Comment by rajkon** [comment]
I created a [Stackoverflow question](https://sqa.stackexchange.com/questions/41642/how-to-get-list-of-files-in-a-directory-recursively-in-cypress ) with the details of versions used to reproduce similar issue` TypeError: fs.readdir is not a function` with Cypress 3.5.0

**Comment by jaslocum** [comment]
I could be totally wrong about this, but I believe that .js files are often run on the server and the client.  I believe that 'fs' will be available when code is running on the server and stubbed for security purposes when executed on the browser.  I used this.$isServer to conditionally determine if the code is being executed on the server or the browser.  This way, I avoid error's when the code is running on the client and 'fs' is not available.

**Comment by elmurphy** [comment]
Hey guys same for me 

```
const fs = require("fs");
console.log(fs);
//output => {}

import * as fs from "fs";
console.log(fs);
//output => {}

import { fs } from "fs";
console.log(fs);
//output => undefined
```

Any suggestion ?

**Comment by goto-bus-stop** [comment]
@elmurphy that code looks expected: in browserify, the `fs` module is an empty object at runtime. It is impossible to use `fs` in the browser because there is no way to access the user's file system. The `brfs` package can transform calls to _specific `fs` functions only_ at build time.

**Comment by jamesstephenbrown** [comment]
Hey guys, total noob here, but I had the same problem and solved it (I think) by changing this:

`var files  = fs.readdirSync(folder);`

To this:

```
var fs = require('fs');
const newLocal = fs.readdirSync(folder);
var files = newLocal;
```
