### ISSUE TITLE
Error: write after end

### ISSUE THREAD

**Issue by lambert-velir** [substack/brfs#38]
I wrote a gulp task using [this](https://medium.com/@sogko/gulp-browserify-the-gulp-y-way-bb359b3f9623) article:

    var browserified = transform(function(filename) {
        var b = browserify(filename);
        b.transform('brfs');
        return b.bundle();
    });

    return gulp.src(src)
        .pipe(browserified)
        .pipe(uglify())
        .pipe(gulp.dest(dest));

When I run this, I get an error: `Error: write after end
    at writeAfterEnd (/www/my-project/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_writable.js:161:12)`

If I comment out the ` b.transform('brfs');`, everything works fine.  Does anyone have any insight as to why this is happening?

Thanks!

**Comment by ibc** [comment]
Which versions of browserify and brfs? None of the above two ways work with browserify 8.1.0 + brfs 1.3.0 (same error as above happens).

**Comment by lambert-velir** [comment]
I'm using:

    "brfs": "^1.2.0",
    "browserify": "^7.0.2",

Looks like I shouldn't upgrade...

**Comment by ibc** [comment]
Just try woth browserify 8.X.X, you'll see :)

**Comment by ibc** [comment]
Please, reopen this issue, it is not fixed at all. It fails with browserify 8.X.X.

**Comment by ibc** [comment]
Still this bug? Neither `bundler.transform('brfs')` or `bundler.transform(require('brfs'))` works:

```
Error: write after end
    at writeAfterEnd (/Users/ibc/eFace2Face/src/DoctoRTCWeb/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:161:12)
    at Labeled.Writable.write (/Users/ibc/eFace2Face/src/DoctoRTCWeb/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:208:5)
    at Producer.ondata (_stream_readable.js:540:20)
    at Producer.emit (events.js:107:17)
    at Producer.Readable.read (_stream_readable.js:373:10)
    at flow (_stream_readable.js:750:26)
    at resume_ (_stream_readable.js:730:3)
    at _stream_readable.js:717:7
    at process._tickDomainCallback (node.js:381:11)
```

The lack of comments from the developer about this issue is frustrating. I know more people with the same issue.

My versions:

* browserify 9.0.3
* brfs 1.4.0

**Comment by Deathspike** [comment]
I don't know the state of the API; everything I tried fails with the same error. I eventually switched to using the CLI, which does seem to work for some obnoxious reason. I'd love to see the API working again as well, or some reaction from the maintainer, but @ibc you might be able to use this meanwhile?

**Comment by NickTomlin** [comment]
Looks like this is an ongoing [issue](https://github.com/substack/node-browserify/issues/1044) with gulp/browserify. I was able to workaround this by using `through2` instead of `transform` (the solution listed [here](https://github.com/substack/node-browserify/issues/1044#issuecomment-72384131)).

**Comment by ibc** [comment]
> but @ibc you might be able to use this meanwhile?

I've been able to use [gulp-brfs](https://github.com/stayradiated/gulp-brfs) and, somehow, fills my needs.

**Comment by substack** [comment]
`b.bundle()` returns a readable stream, not a transform stream. Many of the gulp guides are mistaken on this point but are slowly being fixed. Here's a good fix by @terinjokes for gulp users: https://github.com/substack/node-browserify/issues/1191#issuecomment-89302289
