### ISSUE TITLE
Can this be used if the fs call is within a function?

### ISSUE THREAD

**Issue by tnyeanderson** [substack/brfs#49]
I have the following code (shortened and simplified)

function load(path) {
     fs.readFileSync(path);
}

that is called a few times throughout this module to synchronously load dependencies. Will this plugin be able to handle these kind of calls? Thanks

**Comment by mattdesl** [comment]
No; the path must be statically analyzable. That is; it should not depend on runtime variables. Similar to the ES6 import semantics.
