### ISSUE TITLE
Supporting statSync?

### ISSUE THREAD

**Issue by tume** [substack/brfs#54]
I ran into an issue when trying to use node-config with browserify. It seems to use statSync to check if file exists and only after that read file with readFileSync.

I was wondering if supporting statSync would fit into the scope of this project?

**Comment by mattdesl** [comment]
Does it really make sense? It would only return a true/false boolean of whether that file existed at bundle time. 

Also, it would not work if the subsequent `readFileSync` is not statically analyzable.

**Comment by mattdesl** [comment]
I'm going to close this for the reasons I listed above. Cheers! :smile:
