### ISSUE TITLE
fs.readFileSync() => bundleFile()?

### ISSUE THREAD

**Issue by mikemaccana** [substack/brfs#59]
More a suggestion than an issue. I know `fs,readFileSync()` from node, but bundling a file with `brfs` does something very different from blocking & reading a file at point of execution like fs.readFileSync(). Maybe it would be simpler to use a name that better indicates what's happening? 

Just a thought. Thanks for browserify Substack! 🤖

**Comment by mattdesl** [comment]
Yeah, it is a bit misleading, but the whole purpose of this module is to support a single entry point in Node and the browser, by using the same `fs.readFileSync` statement. :smile:

**Comment by mikemaccana** [comment]
How about defaulting to a sensible name like `fs.bundleFfle()` for most users, and leaving the `.readFileSync()` for folks who want a single entry point between node & the browser?
