### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by DoomyTheFroomy** [substack/brfs#61]
Hi before using this, I was wondering if this project is still maintained? If not, I will have a look for another alternative. 

Kind regards

**Comment by Josh-a-e** [comment]
@DoomyTheFroomy did you find an alternative?

**Comment by DoomyTheFroomy** [comment]
@Josh-a-e no I have used the version before, because this was working!

**Comment by mattdesl** [comment]
Yes, this is still being maintained. I recently got push rights and will try to clean things up when I have time.

Also, the scope of this module is intentionally small. It is not trying to replace `fs` entirely, just cover common situations like statically inlining a file.
